version: '3'

services:
  fastapi:
    build: ./src/
    env_file:
      - .env
    networks:
      - backend
    expose:
      - "8000"
    depends_on:
      - es
      - redis

  nginx:
    image: nginx:latest
    restart: on-failure
    privileged: true
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/site.conf:/etc/nginx/conf.d/site.conf:ro
    depends_on:
      - fastapi
    ports:
      - "80:80"
    networks:
      - backend

  es-dump:
    image: elasticdump/elasticsearch-dump
    container_name: es-dump
    privileged: true
    networks:
      - backend
    volumes:
      - ./es_index:/es_index
      - ./dump.sh:/dump.sh
    depends_on:
      - es
    command: /bin/sh -c "chmod +x dump.sh 
      && ./dump.sh"

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: es
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - backend
    volumes:
      - es-db:/data/es

  redis:
    image: redis:latest
    container_name: redis
    privileged: true
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 50

networks:
  backend:

volumes:
  es-db: